CREATE DATABASE DuplicateIndexColumnError;
SET DATABASE DuplicateIndexColumnError;

CREATE TABLE Estudiante AS (
  ID INTEGER NOT NULL,
  Nombre VARCHAR(30) NOT NULL
);

INSERT INTO Estudiante VALUES(1, "Isaac");
INSERT INTO Estudiante VALUES(2, "Juan");

CREATE INDEX IDX_ID_BST ON Estudiante(ID) OF TYPE BST;

CREATE INDEX IDX_ID_BTREE ON Estudiante(ID) OF TYPE BTREE;